// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DynamicIcon: typeof import('./src/components/DynamicIcon.vue')['default']
    Icon: typeof import('./src/components/Icon.vue')['default']
    IconMdiFormatText: typeof import('~icons/mdi/format-text')['default']
    Nav: typeof import('./src/components/Nav.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WidgetIcon: typeof import('./src/components/WidgetIcon.vue')['default']
    WidgetInstance: typeof import('./src/components/WidgetInstance.vue')['default']
    WidgetRenderer: typeof import('./src/components/WidgetRenderer.vue')['default']
    WidgetRendererVertical: typeof import('./src/components/WidgetRendererVertical.vue')['default']
    WidgetTeaser: typeof import('./src/components/WidgetTeaser.vue')['default']
    WidgetTemplate: typeof import('./src/components/WidgetTemplate.vue')['default']
  }
}
