// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Nav: typeof import('./../components/Nav.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WidgetInstance: typeof import('./../components/WidgetInstance.vue')['default']
    WidgetTemplate: typeof import('./../components/WidgetTemplate.vue')['default']
  }
}
