// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Button: typeof import('./../components/Button.vue')['default']
    CeateurWidgetsSource: typeof import('./../components/CeateurWidgetsSource.vue')['default']
    CreateurWidgetPreview: typeof import('./../components/CreateurWidgetPreview.vue')['default']
    CreateurWidgetsTarget: typeof import('./../components/CreateurWidgetsTarget.vue')['default']
    CreateurWidgetTemplate: typeof import('./../components/CreateurWidgetTemplate.vue')['default']
    CreateurWidgetTemplates: typeof import("../components/CreateurWidgetTemplates.vue")["default"]
    Input: typeof import('./../components/Input.vue')['default']
    ModalWindow: typeof import('./../components/ModalWindow.vue')['default']
    Nav: typeof import('./../components/Nav.vue')['default']
    RouteEditor: typeof import('./../components/RouteEditor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WidgetInstance: typeof import("./../components/WidgetInstance.vue")["default"]
    WidgetTemplate: typeof import("./../components/WidgetTemplate.vue")["default"]
  }
}
